#!/bin/sh

# Instala los paquetes necesarios
rpm-ostree install steam-devices openrgb-udev-rules gnome-shell-extension-blur-my-shell gnome-shell-extension-dash-to-panel gnome-shell-extension-dash-to-dock gnome-shell-extension-appindicator openbox -r
